routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Authentication Routes
Auth::routes();

//Route::get('verifyEmailFirst', 'Auth\RegisterController@verifyEmailFirst')->name('verifyemailfirst');
Route::get('verify/{email}/{verifyToken}', 'Auth\RegisterController@sendEmailDone')->name('sendemaildone');

//pages
Route::get('over-ons', 'PagesController@getAbout')->name('about');
Route::get('werkwijze', 'PagesController@getHowto')->name('howto');

//contact
Route::get('contact', 'ContactController@getContact')->name('contact');
Route::post('contact', 'ContactController@sendContactInfo')->name('contact.sent');

//admin
Route::prefix('admin')->group(function(){
	Route::get('/', 'AdminController@getIndex')->name('admin');
	Route::post('/', 'AdminController@postAdminAssignRoles')->name('admin.assign');
	Route::resource('/categories', 'Post\CategoryController', ['except' => 'show']);
	Route::resource('/tags', 'Post\TagController', ['except' => 'show']);
});

//homepage
Route::get('/', 'PagesController@getIndex');

//divvy collections
//Route::get('collection', 'Post\BlogController@getIndex')->name('category.all');
Route::get('blog/{slug}', 'Post\BlogController@getSingle')->name('blog.single');

Route::get('categories/{category}', 'Post\BlogController@getCategory')->name('category.index');
Route::get('tags/{tag}', 'Post\BlogController@getTag')->name('tag.index');


//post routes
	// Route::post('posts/{post}', 'Post\PostController@update')->name('posts.update');
	// Route::get('posts/{post}/edit', 'Post\PostController@edit')->name('posts.edit');
	// Route::post('posts', 'Post\PostController@store')->name('posts.store');

	Route::resource('posts', 'Post\PostController', ['except' => ['index', 'create']]);
	//
	Route::post('posts/{slug}/comments', 'Post\CommentController@store')->name('comments.store');
	Route::put('posts/{slug}/comments/update', 'Post\CommentController@update')->name('comments.update');
	Route::post('posts/{slug}/comments/reactie/{id}', 'Post\CommentController@reply')->name('comments.reply');

	Route::delete('posts/{slug}/comments/verwijderen', 'Post\CommentController@destroy')->name('comments.destroy');

	//steps
	Route::post('posts/{post}/steps', 'Post\StepController@store')->name('steps.store');
	Route::post('posts/{post}/steps/verwijderen', 'Post\StepController@destroy')->name('steps.destroy');
//

//account
Route::prefix('account')->group(function(){	
	Route::get('/', 'Account\AccountController@edit')->name('account');
	Route::post('/update', 'Account\AccountController@update')->name('account.update');

	//account wachtwoord
	Route::get('/wachtwoord', 'Account\AccountController@password')->name('account.password');
	Route::put('/wachtwoord/update/{user}', 'Account\AccountController@passwordUpdate')->name('password.update');

	//delete account
	Route::get('account_verwijderen', 'Account\AccountController@deleteAccount')->name('delete.account');
	Route::post('account_verwijderen', 'Account\AccountController@destroy')->name('account.destroy');
});

//imageupload
// Route::get('/upload', 'ImageProcessController@upload');
// Route::post('/upload', 'ImageProcessController@postupload');
// Route::post('/cover-image-save', 'ImageProcessController@postimgAdjustpostion');

//profile routes
Route::prefix('{username}')->group(function(){
	Route::get('/profiel', 'Account\ProfileController@getProfile')->name('profile');
	Route::get('/profiel/posts', 'Account\ProfileController@getPosts')->name('user.posts');
});

//user routes
Route::get('drafts', 'Account\UserController@getDrafts')->name('user.drafts');
Route::get('berichten', 'Account\UserController@getMessages')->name('messages');

app/Http/Controllers/Post/BlogController.php
<?php

namespace App\Http\Controllers\Post;

use App\Http\Controllers\Controller;

use App\Models\Post;
use App\Models\Category;
use App\Models\Tag;

use Illuminate\Http\Request;

class BlogController extends Controller
{
    // public function getIndex(){
    // 	$posts = Post::orderBy('created_at', 'desc')
    // 		->paginate(15);

    // 	return view('blog.index', compact('posts'));
    // }

    public function getSingle($slug)
    {
        $post = Post::whereSlug($slug)->firstOrFail();

        $comments = $post->comments->sortBy('created_at')->take(10);

        return view('blog.single', compact('post', 'comments'));
    }

    public function getCategory(Category $category){

        $posts = $category->posts;
        $category = $category->category;

        return view('blog.category.index', compact('posts', 'category'));
    }

     public function getTag(Tag $tag){

        $posts = $tag->posts;
        $tag = $tag->tag;

        return view('blog.tag.index', compact('posts', 'tag'));
    }
}

app/Http/Controllers/Post/CategoryController.php
<?php

namespace App\Http\Controllers\Post;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\Models\Category;

class CategoryController extends Controller
{
	public function __construct()
    {
        $this->middleware('admin');
    }

	protected $fields = [
		'category' => '',
		'meta_description' => '',
	];

	public function index()
	{
		$categories = Category::all();

		return view('admin.category.index')->withCategories($categories);
	}

	public function create()
	{

		return view('admin.category.create');
	}

	public function store(Request $request)
	{
		$this->validate($request, [
            'category' => 'required|min:3|max:144|unique:categories,category',
            'meta_description' => 'min:3|max:255',
        ]);

        $category = new Category;

        $category->category = $request->category;
		$category->meta_description = $request->meta_description;

		$category->save();

		flash()->success("De '$category->category' is aangemaakt.");

		return redirect()->route('categories.index');
	}

	public function edit($id)
	{
		$category = Category::findOrFail($id);
		$data = ['id' => $id];
		
		foreach (array_keys($this->fields) as $field) {
			$data[$field] = old($field, $category->$field);
		}

		return view('admin.category.edit', $data);
	}

	public function update(Request $request, $id)
	{
		$category = Category::findOrFail($id);

		$this->validate($request, [
            'category' => 'required|min:3|max:144|unique:categories,category,'.$category->id,
            'meta_description' => 'min:3|max:255',
        ]);

		$category->category = $request->category;
		$category->meta_description = $request->meta_description;

		$category->save();

		flash()->success('Aanpassingen zijn opgeslagen.');

		return redirect()->route('categories.index');
	}

	public function destroy($id)
	{
		$category = Category::findOrFail($id);
		$category->posts()->detach();
		
		$category->delete();

		flash()->success("De '$category->category' is verwijderd.");

		return redirect()->route('categories.index');
	}
}

app/Http/Controllers/Post/CommentController.php
<?php

namespace App\Http\Controllers\Post;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\Post;
use App\Models\Comment;

use Auth;

class CommentController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth');
    }

    public function store(Request $request, $slug)
    {
    	//find post in db
    	$post = Post::whereSlug($slug)->firstOrFail();

    	//validate
    	$this->validate(request(), [
    		'body' => 'required|min:2|max:2000',
    	]);

    	//add comment to the db
    	$post->addComment(request('body'));

    	//fash message
        flash()->success('Uw reactie is geplaatst!');

    	return back();
    }

    public function update(Request $request, $id)
    {
        $comment = Comment::whereId($id)->firstOrFail();

        $comment->body = $request->edit_body;
        $comment->save();

        //fash message
        flash()->success('Uw reactie is gewijzigd!');

        return back();
    }

    public function reply(Request $request, $slug, $id)
    {
        $post = Post::whereSlug($slug)->firstOrFail();

        //validate
        $this->validate(request(), [
            'reply_body' => 'required|min:2|max:2000',
        ]);

        //add reply to the db
        $post->addComment(request('reply_body'), $id);

        //fash message
        flash()->success('Uw reactie is geplaatst!');

        return back();
    }

    public function destroy($id)
    {
    	//
        $comment = Comment::whereId($id)->firstOrFail();
        $comment->delete();

        flash()->success('De reactie is met succes verwijderd!');

        return back();
    }
}

app/Http/Controllers/Post/PhotoController.php
<?php

namespace App\Http\Controllers\Post;

use App\Http\Requests\PhotoUploadRequest;
use App\Http\Controllers\Controller;

class PhotoController extends Controller
{
    public function upload()
    {
        return view('upload_form');
    }
 
    public function Submit(PhotoUploadRequest $request)
    {
        $photo = Post_photo::create($request->all());
        foreach ($request->photos as $photo) {
            $filename = $photo->store('photos');
            ProductsPhoto::create([
                'post_id' => $post->id,
                'filename' => $filename
            ]);
        }
        return 'Upload successful!';
    }
}

app/Http/Controllers/Post/PostController.php
<?php

namespace App\Http\Controllers\Post;

use App\Http\Controllers\Controller;

use App\Jobs\PostFormFields;
use App\Http\Requests\PostCreateRequest;
use App\Http\Requests\PostUpdateRequest;

use Illuminate\Http\Request;

use App\Models\Post;
use App\Models\Tag;
use App\Models\Step;
use App\Models\Category;

use Auth;
use Session;


class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function store(Request $request)
    {
        //validate the data
        $this->validate($request, [
            'title' => 'required|alpha_spaces|min:3|max:100',
        ]);

        //create post
        $post = Post::create([
            'status' => NULL,
            'user_id' => Auth::user()->id,
            'meta_description' => $request->title,
            'category_id' => NULL,
            'title' => $request->title,
            'post_cover' => 'tumb.jpg',
            'step_count' => 1,
        ]);

        //create first step
        $post->addStep();

        //give postcontroller the right slug
        $slug = $post->slug;

        return redirect()->route('posts.edit', compact('slug'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $post = Post::whereSlug($slug)->firstOrFail();

        return view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        $data = $this->dispatch(new PostFormFields($slug));

        return view('posts.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostUpdateRequest $request, $slug)
    {
        $this->validate($request, [
            'step-title-.*' => 'required|min:3',
            'step-body-.*' => 'required|min:3',
        ]);

        //
        $post = Post::whereSlug($slug)->firstOrFail();
        $post->fill($request->postFillData());

        //$post->setTitleAttribute($post->title);
        //$post->setUniqueSlug($post->title, '');

        //get category id
        $category = $request->category;
        $post->category_id = Category::whereCategory($category)->firstOrFail()->id;

        //save steps in db
        foreach($request->get('step-title-') as $key => $val) {

            $step_nr = $key + 1;
            $step = Step::firstOrNew([
                'post_id' => $post->id,
                'step_nr' => $step_nr
            ]);
            //$step = Step::wherePost_id($post->id)->whereStep_nr($step_nr)->firstOrFail();

            $step->post_id = $post->id;
            $step->step_nr = $step_nr;
            $step->title = $request->input('step-title-')[$key];
            $step->body = $request->get('step-body-')[$key];

            $step->save();

            //save the number of steps
            $post->step_count = $step->step_nr;
        }

        $post->save();
        $post->syncTags($request->get('tags', []));

        if ($request->has('save')) {
            flash()->success('De post is opgeslagen.');
            return redirect()->back();

        } else if ($request->has('publish')) {
            return redirect()->route('user.posts', Auth::user()->username);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        dd('removed');
        //
        $post = Post::whereSlug($slug)->firstOrFail();
        $post->tags()->detach();
        //Storage::delete($post->image);
        
        $post->delete();

        flash()->success('Post is met succes verwijderd!');

        //belangrijk om terug te komen bij eigen posts
        $user = Auth::user();

        return redirect()->route('user.posts', compact('user'));
    }
}

app/Http/Controllers/Post/StepController.php
<?php

namespace App\Http\Controllers\Post;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

use App\Models\Step;
use App\Models\Post;

class StepController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $slug)
    {
        $post = Post::whereSlug($slug)->firstOrFail();

        //increment step count
        $i = $post->step_count;
        $i++;
        $post->step_count = $i;


        $post->save();

        //add step
        $step = new Step;

        $step->post_id = $post->id;
        $step->step_nr = $i;

        $step->save();

        //return 'Step created';
    }

    public function destroy($id)
    {  
        $step = Step::whereId($id)->firstOrFail();

        //change post steps
        $post = Post::whereId($step->post_id)->firstOrFail();
        $steps = $post->step_count;
        $post->step_count = $steps - 1;
        $post->save();

        $step->delete();

        return back();
    }
}

app/Http/Controllers/Post/TagController.php
<?php

namespace App\Http\Controllers\Post;

use App\Http\Controllers\Controller;

use App\Http\Requests\TagCreateRequest;

use Illuminate\Http\Request;
use App\Models\Tag;

class TagController extends Controller
{
	public function __construct()
    {
        $this->middleware('admin');
    }

	protected $fields = [
		'tag' => '',
		'meta_description' => '',
	];

	public function index()
	{
		$tags = Tag::all();

		return view('admin.tag.index')->withTags($tags);
	}

	public function create()
	{
		$data = [];
		foreach ($this->fields as $field => $default) {
			$data[$field] = old($field, $default);
		}

		return view('admin.tag.create', $data);
	}

	public function store(TagCreateRequest $request)
	{
		$tag = new Tag();

		foreach (array_keys($this->fields) as $field) {
			$tag->$field = $request->get($field);
		}

		$tag->save();

		flash()->success("De '$tag->tag' is aangemaakt.");

		return redirect()->route('tags.index');
	}

	public function edit($id)
	{
		$tag = Tag::findOrFail($id);
		$data = ['id' => $id];
		
		foreach (array_keys($this->fields) as $field) {
			$data[$field] = old($field, $tag->$field);
		}

		return view('admin.tag.edit', $data);
	}

	public function update(Request $request, $id)
	{
		$tag = Tag::findOrFail($id);

		$this->validate($request, [
            'tag' => 'required|min:3|max:144|unique:tags,tag,'.$tag->id,
            'meta_description' => 'nullable|min:3|max:255',
        ]);

		$tag->tag = $request->tag;

		foreach (array_keys(array_except($this->fields, ['tag'])) as $field) {
			$tag->$field = $request->get($field);
		}

		$tag->save();

		flash()->success('Aanpassingen zijn opgeslagen.');

		return redirect()->route('tags.index');
	}

	public function destroy($id)
	{
		$tag = Tag::findOrFail($id);
		$tag->posts()->detach();
		
		$tag->delete();

		flash()->success("De '$tag->tag' is verwijderd.");

		return redirect()->route('tags.index');
	}
}

resources/views/posts/edit.blade.php
@extends('layouts.main')

@section('title', '| Create new post')

@section('stylesheets')
	<!-- page exclusive styles -->
	<link rel="stylesheet" href="{{ asset('css/posts.css') }}">
	<link rel="stylesheet" href="{{ asset('css/selectize.css') }}">

	<!--standaard jquery staat in head-->
	
	<!--script voor drag and drop functies-->
	<script type="text/javascript" src="{{asset('js/jquery-ui.js')}}"></script>
	
	<!--script voor de add and remove functie-->

@endsection

@section('content')

	<div id="ajaxResponse"></div>

	<div class="row">

		<form class="" role="form" method="POST" action="{{ route('posts.update', $slug) }}" id="form-add-post">
			{{ csrf_field() }}
			{{ method_field('PUT') }}

			<div class="col-md-12">
				<div class="card">
					<div class="card-header card-top card-success">
						{{-- title --}}
						<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">					
							<label for="title"><h3>Titel:</h3></label>
								<input type="text" class="form-control input-lg" id="title" name="title" required="true" value="{{ old('title', $post->title) }}" placeholder="Geef je project hier een titel">
								
								@if ($errors->has('title'))
				                    <span class="help-block">
				                        <strong style="color: #fff !important;">{{ $errors->first('title') }}</strong>
				                    </span>
				                @endif
						</div>
					</div>
				</div>
			</div>

			<div class="col-md-8">
				<div id="step-box-group">

					<!-- old stepboxes -->
					@foreach($post->steps as $i => $step)
						{{-- old steps --}}
						<div id="step-box-{{ $i }}" class="card step-box">
							<div class="card-header step-box-title">
								<div class="pull-right">
									<a type="button" class="btn btn-sm btn-danger delete-step" data-toggle="modal" data-step_nr="step-box-{{ $i }}" data-step_id="{{ $step->id }}" data-target="#delete-step-modal" data-delete_link="{{ route('steps.destroy', $step->id) }}"><i class="fa fa-times-circle"></i> Stap verwijderen</a>
								</div>
								<h4>(old) Stap {{ $step->step_nr }}</h4>
							</div>
							<div class="card-body">
								{{-- step form --}}
								<div class="form-group{{ $errors->has('step-title-.'.$i) ? ' has-error' : '' }}">
									<label for="step-title-{{ $i }}" class="control-label">Titel</label>
									<input type="text" class="form-control" placeholder="Titel" name="step-title-[]" id="step-title-{{ $i }}" value="{{ old('step-title-.'.$i, $step->title) }}">
								</div>
								<div class="form-group{{ $errors->has('step-body-.'.$i) ? ' has-error' : '' }}">
									<label for="step-body-{{ $i }}" class="control-label">Omschrijving</label>
									<textarea class="form-control" rows="4" placeholder="Beschrijf hier de stap..." name="step-body-[]" id="step-body-{{ $i }}">{{ old('step-body-.'.$i, $step->body) }}</textarea>
								</div>
							</div>
						</div>
					@endforeach
				</div>
			</div>

			<!-- Post info -->
			<div class="col-md-4">
				<div class="card post-well">
					<h3>Informatie</h3>
	            	<hr>
	        		{{-- categories --}}
	        		<div class="form-group{{ $errors->has('category') ? ' has-error' : '' }}">
						<label for="category">Categorie:</label>
						<select name="category" id="category" class="demo-default" placeholder="Kies een categorie...">
							<option value="">Kies een categorie...</option>
							@foreach ($allcategories as $category)
								<option data-selectable="" @if (in_array($category, $categories)) selected @endif value="{{ $category }}">{{ $category }}</option>
							@endforeach
						</select>
						@include('errors.partials._formerrors', ['errorName' => 'category'])

					</div>

					{{-- tags --}}
	            	<div class="form-group{{ $errors->has('tags') ? ' has-error' : '' }}">
						<label for="tags">Tags:</label>
						<select name="tags[]" id="tags" class="form-control" placeholder="Voeg tags toe..." multiple>
							@foreach ($allTags as $tag)
					            <option @if (in_array($tag, $tags)) selected @endif value="{{ $tag }}">{{ $tag }}</option>
					         @endforeach
						</select>
						@include('errors.partials._formerrors', ['errorName' => 'tags'])
					</div>
					<hr>
					<input class="btn btn-warning btn-lg" type="submit" value="Opslaan" name="save" id="form-add-post"></input>
				</div>
			</div>
		</form>

		<!-- </form> -->
		<div class="col-md-8">
			<form class="" role="form" method="POST" action="{{ route('steps.store', $post->slug) }}">
				{{ csrf_field() }}
				<a href="#_" class="btn btn-success" id="add-step">Stap toevoegen</a>
				<!-- <button class="btn btn-success" type="submit" id="add-step">Stap toevoegen</button> -->
			</form>
		</div>

		{{-- delete step modal --}}
		<div class="modal fade" id="delete-step-modal" tabindex="-1" role="dialog" aria-labelledby="">
		 	<div class="modal-dialog modal-sm" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title">Weet je zeker dat je deze stap wilt verwijderen?</h4>
					</div>
					<div class="modal-footer">
						<form class="" role="form" method="POST" id="remove-step-form" action="">
							{{ csrf_field() }}
							{{ method_field('DELETE') }}

							<button type="button" class="btn btn-lg btn-warning" data-dismiss="modal">Terug</button>
							<input class="btn btn-danger" type="submit" value="Verwijder" name="delete" id="remove-step" data-dismiss="modal"></input>
						</form>
					</div>
				</div>
			</div>
		</div>
	
	</div> <!-- end row -->

@endsection

@section('scripts')
	{{-- tour --}}
	<script src="{{ asset('js/selectize.js') }}"></script>
	
	<script type="text/javascript">
		$(document).ready(function() {

			//global variables
			var counter = {{ $post->step_count }} + 1;
			var step_nr = null;
			var step_remove_url = null;

			//fixed sidebar
			$('.post-well').affix({
				offset: {
				    top: 210,
			  	}
			})

			$("#step-box-group").sortable({
				stop: function (event, ui) {
					var children = $(this).children("div.step-box");
					children.each(function (index) {
						var l = $(this).find(".step-box-title");
						var html = "<h4>(new) Stap " + (index + 1) + "</h4>";
						l.html(html);
					});
				}
			});

			/*_______________________
			 | add steps function    |
			 |______________________*/

		    $("#add-step").click(function () {

				if(counter > 30) {
					alert("Helaas is het niet toegestaan meer dan 30 stappen te gebruiken.");
					return false;
				}

				var newStep = $(document.createElement('div'))
					.attr("id", 'step-box-' + counter)
					.attr("class", 'card step-box'); //class toevoeging

				newStep.after().html('<div class="card-header step-box-title"><h4>(new)&nbsp;Stap&nbsp;'+ counter + '&nbsp;</h4></div>' + '<div class="card-body"><div class="form-group"><label for="step-title-' + counter + '" class="control-label">Title</label><input type="text" class="form-control" placeholder="Titel" id="step-title-' + counter + '" name="step-title-[]"></div>' + '<div class="form-group"><label for="step-body-' + counter + '" class="control-label">Omschrijving</label><textarea class="form-control" rows="4" placeholder="Beschrijf hier de stap..." name="step-body-[]" id="step-body-'+ counter + '"></textarea></div></div></div>');

				newStep.appendTo("#step-box-group"); //voegt de nieuwe div toe aan deze class of id
				
				counter++;
			});

			//pass step id to delete modal
			$('.delete-step').click(function () {
				stepNr = $(this).data('step_nr');

				//step_remove_url = $(this).data('delete_link');
				step_remove_url = '{{ URL::route('steps.destroy', $step->id) }}';

				//console.log(counter);
			});

			//remove step dynamic
		    $("#remove-step").click(function (e) {
				if(counter == 2) {
					alert("Je moet minimaal één stap omschrijven.");
					return false;
				} else {
					//remove dynamic step
					$("#" + stepNr).remove();

					//reorder stepcount
					var children = $("#step-box-group").children("div.step-box");
					children.each(function (index) {
						var l = $(this).find(".step-box-title");
						var html = "<h4>(new) Stap " + (index + 1) + "</h4>";
						l.html(html);
					});

					e.preventDefault();

					//delete post data
					$.ajax({
						type: 'POST',
						url: step_remove_url,
						data: {
							'_token': $('input[name=_token]').val(),
						},
					});

					step_remove_url = null;

					//save new data
					//$( "#form-add-post" ).submit();
				}

				counter--;
			});

			/*________________
			 | selectize      |
			 |________________*/

			//categories
			$('#category').selectize({
				create: false,
				sortField: {
					field: 'text',
					//direction: 'asc'
				},
				dropdownParent: 'body'
			});

			//tags
			$(function() {
				$("#tags").selectize({
					create: true,
					maxItems: 15,
				});
			});

			//submit step
			// $('#add-step').click(function(e){
			// 	e.preventDefault();

			// 	//post data
			// 	$.ajax({
			// 		type: 'POST',
			// 		url: '{{ URL::route('steps.store', $post->slug) }}',
			// 		data: {
			// 			'_token': $('input[name=_token]').val(),
			// 		},
			// 	});
			// });
		
		});
	</script>

@stop

resources/views/posts/show.blade.php
@extends('layouts.main')

@section('title', '| title')

@section('stylesheets')
	<!-- page exclusive styles -->
    <link rel="stylesheet" href="{{ asset('css/posts.css') }}">

@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <!-- Post header -->
            <div class="card card-success">
                <div class="post-title">
                    <h2>{{ $post->title }}<small> Door <a href="">{{ucfirst($post->user->username)}}</a> in <a href="">Houtbewerking</a></small></h2>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="post-cover">
                    <div class="image">
                        <img src="{{ asset('img/post/cover.jpg') }}">
                    </div>

                </div>
                    
            </div>

            <!-- Post Body -->
            <div class="post-body">

                <!-- Post step (preview)  -->
                    <div class="card">
                        <div class="step-header" id="step-1">
                            <div class="">
                                <img src="{{ asset('img/post/step1.jpg') }}">
                            </div>
                        </div>

                        <div class="step-content">
                            <h4>Stap 1: Benodigdheden</h4>
                            <hr>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam vitae justo gravida justo mollis laoreet quis sed quam. Integer justo ex, pellentesque sit amet mattis sit amet, dictum sit amet nisl. Nunc euismod, tellus non sollicitudin venenatis.

                                <ul>
                                    <li>Sed facilisis</li>
                                    <li>Aenean</li>
                                    <li>maximus nisi</li>
                                </ul>

                                dui volutpat augue, quis tincidunt ipsum nulla eget erat.
                            </p>
                        </div>
                    </div>

            </div>
        </div>

        <!-- Post info -->
        <div class="col-md-4">
            <div class="card post-well">
                <div class="center">
                    <h3>Menu</h3>
                    <hr>
                    <div class="post-meta">
                        <hr>
                    </div>
                    <div class="well-info">
                        <a class="btn btn-success" href="{{ route('posts.edit', $post->slug) }}"><i class="fa fa-pencil"></i> Aanpassen</a>
                        <a class="btn btn-info" href="{{ route('blog.single', $post->slug) }}"><i class="fa fa-eye"></i> Bekijken</a>
                        <hr>
               
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-delete">
                            <i class="fa fa-times-circle"></i> Verwijderen
                        </button>


                        {{-- confirm delete --}}
                        <div class="modal fade" id="modal-delete" tabIndex="-1">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">×</button>
                                        <h4 class="modal-title">Post verwijderen</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p class="lead">
                                            Weet je zeker dat je deze post wilt verwijderen?
                                        </p>
                                    </div>
                                    <div class="modal-footer">
                                        <form method="POST" action="{{ route('posts.destroy', $post->id) }}">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="DELETE">
                                            <button type="button" class="btn btn-default"
                                            data-dismiss="modal">Nee</button>
                                            <button type="submit" class="btn btn-danger">
                                                <i class="fa fa-times-circle"></i> Ja
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <hr>
                        <div>
                            <button class="btn btn-block" onclick="goBack()">Terug</button>
                        </div>

                        <hr>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

@endsection

@section('scripts')
	<!-- page exclusive scripts -->
@stop