routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Authentication Routes
Auth::routes();

//Route::get('verifyEmailFirst', 'Auth\RegisterController@verifyEmailFirst')->name('verifyemailfirst');
Route::get('verify/{email}/{verifyToken}', 'Auth\RegisterController@sendEmailDone')->name('sendemaildone');

//pages
Route::get('over-ons', 'PagesController@getAbout')->name('about');
Route::get('werkwijze', 'PagesController@getHowto')->name('howto');

//contact
Route::get('contact', 'ContactController@getContact')->name('contact');
Route::post('contact', 'ContactController@sendContactInfo')->name('contact.sent');

//admin
Route::prefix('admin')->group(function(){
	Route::get('/', 'AdminController@getIndex')->name('admin');
	Route::post('/', 'AdminController@postAdminAssignRoles')->name('admin.assign');
	Route::resource('/categories', 'Post\CategoryController', ['except' => 'show']);
	Route::resource('/tags', 'Post\TagController', ['except' => 'show']);
});

//homepage
Route::get('/', 'PagesController@getIndex');

//divvy collections
//Route::get('collection', 'Post\BlogController@getIndex')->name('category.all');
Route::get('blog/{slug}', 'Post\BlogController@getSingle')->name('blog.single');

Route::get('categories/{category}', 'Post\BlogController@getCategory')->name('category.index');
Route::get('tags/{tag}', 'Post\BlogController@getTag')->name('tag.index');


//post routes
	// Route::post('posts/{post}', 'Post\PostController@update')->name('posts.update');
	// Route::get('posts/{post}/edit', 'Post\PostController@edit')->name('posts.edit');
	// Route::post('posts', 'Post\PostController@store')->name('posts.store');

	Route::resource('posts', 'Post\PostController', ['except' => ['index', 'create']]);
	//
	Route::post('posts/{slug}/comments', 'Post\CommentController@store')->name('comments.store');
	Route::put('posts/{slug}/comments/update', 'Post\CommentController@update')->name('comments.update');
	Route::post('posts/{slug}/comments/reactie/{id}', 'Post\CommentController@reply')->name('comments.reply');

	Route::delete('posts/{slug}/comments/verwijderen', 'Post\CommentController@destroy')->name('comments.destroy');

	//steps
	Route::post('posts/{post}/steps', 'Post\StepController@store')->name('steps.store');
	Route::post('posts/{post}/steps/verwijderen', 'Post\StepController@destroy')->name('steps.destroy');
//

//account
Route::prefix('account')->group(function(){	
	Route::get('/', 'Account\AccountController@edit')->name('account');
	Route::post('/update', 'Account\AccountController@update')->name('account.update');

	//account wachtwoord
	Route::get('/wachtwoord', 'Account\AccountController@password')->name('account.password');
	Route::put('/wachtwoord/update/{user}', 'Account\AccountController@passwordUpdate')->name('password.update');

	//delete account
	Route::get('account_verwijderen', 'Account\AccountController@deleteAccount')->name('delete.account');
	Route::post('account_verwijderen', 'Account\AccountController@destroy')->name('account.destroy');
});

//imageupload
// Route::get('/upload', 'ImageProcessController@upload');
// Route::post('/upload', 'ImageProcessController@postupload');
// Route::post('/cover-image-save', 'ImageProcessController@postimgAdjustpostion');

//profile routes
Route::prefix('{username}')->group(function(){
	Route::get('/profiel', 'Account\ProfileController@getProfile')->name('profile');
	Route::get('/profiel/posts', 'Account\ProfileController@getPosts')->name('user.posts');
});

//user routes
Route::get('drafts', 'Account\UserController@getDrafts')->name('user.drafts');
Route::get('berichten', 'Account\UserController@getMessages')->name('messages');

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
	protected $fillable = [
		'tag', 'meta_description',
	];

	public function posts()
	{
		return $this->belongsToMany('App\Models\Post', 'posts_tags');
	}

	public static function addNeededTags(array $tags)
	{
		if (count($tags) === 0) {
			return;
		}

		$found = static::whereIn('tag', $tags)->pluck('tag')->all();

		foreach (array_diff($tags, $found) as $tag) {
	  		static::create([
			    'tag' => $tag,
			    'meta_description' => '',
		 	]);
		}
	}

	public function getRouteKeyName()
	{
		return 'tag';
	}
	
}

app/Http/Controllers/Post/TagController.php
<?php

namespace App\Http\Controllers\Post;

use App\Http\Controllers\Controller;

use App\Http\Requests\TagCreateRequest;

use Illuminate\Http\Request;
use App\Models\Tag;

class TagController extends Controller
{
	public function __construct()
    {
        $this->middleware('admin');
    }

	protected $fields = [
		'tag' => '',
		'meta_description' => '',
	];

	public function index()
	{
		$tags = Tag::all();

		return view('admin.tag.index')->withTags($tags);
	}

	public function create()
	{
		$data = [];
		foreach ($this->fields as $field => $default) {
			$data[$field] = old($field, $default);
		}

		return view('admin.tag.create', $data);
	}

	public function store(TagCreateRequest $request)
	{
		$tag = new Tag();

		foreach (array_keys($this->fields) as $field) {
			$tag->$field = $request->get($field);
		}

		$tag->save();

		flash()->success("De '$tag->tag' is aangemaakt.");

		return redirect()->route('tags.index');
	}

	public function edit($id)
	{
		$tag = Tag::findOrFail($id);
		$data = ['id' => $id];
		
		foreach (array_keys($this->fields) as $field) {
			$data[$field] = old($field, $tag->$field);
		}

		return view('admin.tag.edit', $data);
	}

	public function update(Request $request, $id)
	{
		$tag = Tag::findOrFail($id);

		$this->validate($request, [
            'tag' => 'required|min:3|max:144|unique:tags,tag,'.$tag->id,
            'meta_description' => 'nullable|min:3|max:255',
        ]);

		$tag->tag = $request->tag;

		foreach (array_keys(array_except($this->fields, ['tag'])) as $field) {
			$tag->$field = $request->get($field);
		}

		$tag->save();

		flash()->success('Aanpassingen zijn opgeslagen.');

		return redirect()->route('tags.index');
	}

	public function destroy($id)
	{
		$tag = Tag::findOrFail($id);
		$tag->posts()->detach();
		
		$tag->delete();

		flash()->success("De '$tag->tag' is verwijderd.");

		return redirect()->route('tags.index');
	}
}

resources/views/admin/tag/create.blade.php
@extends('layouts.main')

@section('title', '| Tag aanmaken')

@section('stylesheets')
	<!-- page exclusive styles -->
@endsection

@section('content')
	<!-- content -->
	<div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="card">
                <div class="card-header">
                    <h3><a href="{{ route('tags.index') }}">Tags</a> <small>Nieuwe tag toevoegen</small></h3>
                </div>
                <div class="card-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('tags.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('tag') ? ' has-error' : '' }}">
                            <label for="tag" class="col-md-4 control-label">Tag</label>

                            <div class="col-md-6">
                                <input id="tag" type="text" class="form-control" name="tag" value="{{ old('tag') }}" autofocus>
                                @include('errors.partials._formerrors', ['errorName' => 'tag'])
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('meta_description') ? ' has-error' : '' }}">
                            <label for="meta_description" class="col-md-4 control-label">Omschrijving</label>

                            <div class="col-md-6">
                                <textarea id="meta_description" type="text" class="form-control" name="meta_description">{{ old('meta_description') }}</textarea>
                                @include('errors.partials._formerrors', ['errorName' => 'meta_description'])
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-success pull-right btn-right">
                                	<i class="fa fa-plus-circle"></i>
                                    Voeg toe
                                </button>
                                <button onclick="goBack()" class="btn btn-default pull-right">Terug</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
	<!-- page exclusive scripts -->
@stop

resources/views/admin/tag/edit.blade.php
@extends('layouts.main')

@section('title', '| Tag aanpassen')

@section('stylesheets')
	<!-- page exclusive styles -->

@endsection

@section('content')
	<!-- content -->
	<div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="card">
                <div class="card-header">
                    <h3><a href="{{ route('tags.index') }}">Tags</a> <small>tag bewerken</small></h3>
                </div>
                <div class="card-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('tags.update', $id) }}">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}

                        <div class="form-group{{ $errors->has('tag') ? ' has-error' : '' }}">
                            <label for="tag" class="col-md-4 control-label">Tag</label>

                            <div class="col-md-6">
                                <input id="tag" type="text" class="form-control" name="tag" value="{{ $tag }}" autofocus>
                                @include('errors.partials._formerrors', ['errorName' => 'tag'])
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('meta_description') ? ' has-error' : '' }}">
                            <label for="meta_description" class="col-md-4 control-label">Omschrijving</label>

                            <div class="col-md-6">
                                <textarea id="meta_description" type="text" class="form-control" name="meta_description">{{ $meta_description }}</textarea>
                                @include('errors.partials._formerrors', ['errorName' => 'meta_description'])
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4 margin-bottom">
                                <button type="submit" class="btn btn-success pull-right">
                                	<i class="fa fa-plus-circle"></i>
                                    Update
                                </button>
                                <button type="button" class="btn btn-danger btn-md" data-toggle="modal" data-target="#modal-delete">
                                    <i class="fa fa-times-circle"></i> Delete
                                </button>
                            </div>
                            <div class="col-md-6 col-md-offset-4">
                                <button onclick="goBack()" class="btn btn-default pull-right">Terug</button>
                            </div>
                        </div>
                    </form>
                </div>

                {{-- confirm delete --}}
                <div class="modal fade" id="modal-delete" tabIndex="-1">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">
                            ×
                          </button>
                          <h4 class="modal-title">Tag verwijderen</h4>
                        </div>
                        <div class="modal-body">
                          <p class="lead">
                            <i class="fa fa-question-circle fa-lg"></i>  
                            Weet je zeker dat je deze tag wil verwijderen?
                          </p>
                        </div>
                        <div class="modal-footer">
                          <form method="POST" action="{{ route('tags.destroy', $id) }}">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="DELETE">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Nee</button>
                            <button type="submit" class="btn btn-danger"><i class="fa fa-times-circle"></i> Ja</button>
                          </form>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
	<!-- page exclusive scripts -->
@stop

resources/views/admin/tag/index.blade.php
@extends('layouts.main')

@section('title', '| Tags')

@section('stylesheets')
	<!-- page exclusive styles -->

@endsection

@section('content')
	<!-- content -->
	<div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="card">
                <div class="card-header card-top">
                    <h3><a href="{{ route('tags.index') }}">Tags</a> <small> Lijst</small></h3>
                </div>
                <div class="card-body">
                    <div class="pull-right">
                        <a href="{{ route('tags.create') }}" class="btn btn-success margin-bottom">
                            <i class="fa fa-plus-circle"></i> Tag toevoegen
                        </a>
                    </div>

                    <table id="tags-table" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Tag</th>
                                <th class="hidden-md">Omschrijving</th>
                                <th data-sortable="false">Acties</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($tags as $tag)
                        <tr>
                            <td>{{ $tag->tag }}</td>
                            <td class="hidden-md">{{ $tag->meta_description }}</td>
                            <td>
                                <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-info">
                                    <i class="fa fa-pencil"></i> Aanpassen
                                </a>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
	<!-- page exclusive scripts -->
{{--       <script>
    $(function() {
      $("#tags-table").DataTable({
      });
    });
  </script> --}}
@stop